apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  params:
    - name: IMAGE
      description: The image to build and push
      type: string
    - name: repo-url
      description: The git repository URL
      type: string
      default: "https://github.com/sb9462008-creator/tax-calculator"
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
    - name: npminstall
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE)
