apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline-run
spec:
  pipelineRef:
    name: cd-pipeline
  params:
    - name: repo-url
      value: "https://github.com/sb9462008-creator/tax-calculator"
    - name: branch
      value: "main"
    - name: build-image
      value: "us.icr.io/sn-labs-sb9462008/tax-calculator:latest"
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
