apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
      description: The workspace containing the source code
  params:
    - name: PATH_CONTEXT
      description: The path to the source code
      default: .
      type: string
  steps:
    - name: npm-install
      image: node:lts
      workingDir: $(workspaces.source.path)
      command: ["/bin/bash", "-c"]
      args:
        - npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
      description: The workspace containing the source code
  params:
    - name: PATH_CONTEXT
      description: The path to the source code
      default: .
      type: string
  steps:
    - name: jasmine-tests
      image: node:lts
      workingDir: $(workspaces.source.path)
      command: ["/bin/bash", "-c"]
      args:
        - npx jasmine
