apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  steps:
    - name: npm-install
      image: node:lts
      workingDir: $(workspaces.source.path)
      command: ["npm"]
      args: ["install"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: jasmine-tests
      image: node:lts
      workingDir: $(workspaces.source.path)
      command: ["npx"]
      args: ["jasmine"]
